#import "../utils.typ": *
= Discussion

The present study aimed to replicate masculinity threat effects and examine their motivational moderators in a German sample. Contrary to the hypotheses, the results did not reveal the predicted increases in aggressive or anxious cognition following a masculinity threat. Furthermore these relationships were not moderated by pressured or autonomous motivation to behave masculine. While these results contrast with previous findings, the following section examines various factors that may have contributed to the absence of these effects.

== Absence of Masculinity Threat Effects

=== Experimental Manipulation

The experimental manipulation of masculinity threat appeared to be robust. Manipulation checks confirmed that participants correctly recalled the performance feedback from the Gender Knowledge Test, and those in the threat condition reported a significant decrease in their self-evaluated masculinity compared to the control group. This indicates that the study successfully induced a cognitive appraisal of threat to masculine identity. Consequently, the absence of hypothesized effects is likely not attributable to a failure of the experimental induction itself.

=== Sample Considerations

The study’s ability to detect the consequences of the masculinity threat was influenced by the discrepancy between the planned and achieved sample size. While the research design targeted a final analytical sample of 208 participants to ensure sufficient power for all hypothesized effects, the final sample available for analysis consisted of 154 participants. This shortfall was the result of recruitment reaching 196 participants due to fixed time constraints, coupled with a substantial attrition rate of approximately 22% during the data cleaning process.
The high exclusion rate may be attributable to the academic composition of the sample. Research-savvy populations are often more prone to suspicion, and the online format of the study likely contributed to reduced levels of participant engagement.
Consequently, the final analytical sample was approximately 26% smaller than the intended target of 208. Nevertheless, post-hoc power analysis indicated that the study still maintained high power ($1 - beta = .96$) to detect the hypothesized medium-sized effect ($d = 0.55$) of the masculinity threat. While the power was indeed insufficient to detect the smaller moderation effects ($1 - beta = .56$), the robust power for the main effect suggests that the absence of a primary masculinity threat effect is likely not attributable to the diminished sample size alone.

=== Issues with Dependent Measures

The most plausible explanation for the absence of significant effects concerns the poor measurement quality of the Word Fragment Completion Task. While the manipulation successfully induced a threat, the instrument used to capture the resulting cognitive state proved unreliable, as evidenced by extremely poor internal consistency ($alpha$ as low as $.09$) and inadequate sampling adequacy (KMO $< .30$).
This lack of reliability likely stems from the inherent difficulty of designing a Word Fragment Completion Task that isolates specific cognitive activation from "lexical noise." In any language, a participant’s completion of a fragment is influenced by a multitude of factors unrelated to the experimental threat, such as individual vocabulary size, word frequency, and "orthographic neighborhood density"—the number of alternative words that can be formed from a single fragment.

While it is theoretically possible to construct a valid Word Fragment Completion Task in German, doing so requires balancing these complex lexical variables to ensure that the target word is neither too obvious nor too obscure. In the present study, the high level of measurement error suggests that these uncontrolled factors may have overwhelmed the subtle signal of threat-induced cognitive activation. This mirrors the findings of #cite(<kugler2022>, form: "prose"), who demonstrated that while German Word Fragment Completion Task can track stable trait aggression, they struggle to capture the acute, state-level shifts in cognition required for experimental research.

== Measuring Masculinity Threat Effects

The psychometric failure of the Word Fragment Completion Task highlights a broader challenge in masculinity research: the difficulty of selecting a measure that effectively balances social desirability bias, construct validity, and the ability to differentiate between distinct threat responses.
This necessitates a careful weighing of alternative formats that might better optimize the trade-off between sensitivity and reliability in future studies. The following sections provide an overview of the various measures that can be administered to capture masculinity threat responses.

=== Self-Report & Attitudinal Measures

Explicit self-report measures of emotional states offer high face validity and are well-established in psychological research as a primary method for capturing subjective experience #citeWithPrefix(prefix: "e.g. ", keys: <robinson2002belief>). Several studies have successfully assessed masculinity threat responses through self-reported emotions such as anger, shame, pride, and public discomfort @valved2021gender @vescio2025masculinity. 
However, this approach faces two significant limitations. First, it is highly susceptible to social desirability bias: reporting feelings of anxiety or shame may itself be perceived as unmasculine, leading men to underreport these responses. This concern is particularly acute in this context, as masculine identity threat is tied to concerns about appearing insufficiently masculine. Second, self-reports rely on the assumption that individuals possess the necessary introspective awareness to accurately identify their internal states.

An alternative approach involves assessing threat responses through attitudinal outcomes. Masculinity threats have been shown to increase the justification of social inequality @weaver2015justification or tolerance for sexual violence @vescio2025masculinity. 
These measures offer a balance between practical feasibility and construct validity, as attitudes can be assessed through standard questionnaire formats while remaining less transparent than direct emotion reports. 
However, attitudinal measures may be particularly problematic in highly educated samples, where baseline support of discriminatory attitudes tends to be low. 
Furthermore, attitudinal measures fail to distinguish between internalized and externalized responses. Because a single reported attitude can stem from either defensive aggression or an underlying state of anxiety, these measures capture the evaluative "output" of a threat rather than the specific cognitive or affective process that triggered it.

=== Implicit Measures and Associative Tasks

Implicit measures are typically chosen to bypass the social desirability bias and the lack of introspective awareness often found in self-reports. By measuring automatic cognitions, these tasks can theoretically detect genuine threat effects without relying on a participant’s willingness or ability to report them @vandello2008precarious.
The Word Fragment Completion Task was selected for this study to capture these processes. However, it failed to serve as a reliable measure, highlighting the difficulty of constructing a task sensitive enough to capture experimental effects over the "noise" of individual linguistic differences.

To retain the advantages of implicit testing while avoiding the lexical noise of word fragments, researchers might instead employ associative tasks like the Implicit Association Test (IAT) @egloff2002predictive. Rather than relying on the spontaneous completion of fragments, the IAT measures the relative strength of associations between concepts (e.g., "Self" and "Weakness"). While this format is less influenced by individual vocabulary differences, its validity for capturing acute, state-level shifts following an experimental manipulation is highly questionable.
Research has found that implicit formats often fail to register significant changes following experimental inductions @schmukle2004does. In the specific context of masculinity threat, the extensive length of the IAT presents a critical procedural limitation. The cognitive effort and time required to complete the numerous trials likely allow the short-lived psychological state triggered by the threat to resolve before it can be accurately measured.

=== Behavioral Measures

Behavioral measures provide perhaps the most direct assessment of threat-relevant outcomes by capturing real-world actions rather than reported feelings. Research has demonstrated masculinity threat effects through proxies such as the voluntary administration of electrical shocks @fowler2017does. This measure effectively bypasses conscious filtration, as participants are often unaware that their actions serve as a defensive response to a psychological threat. While traditional behavioral approaches are often resource-intensive, future research could utilize game-like paradigms to measure masculinity threat responses in a more scalable, online-compatible format.

The primary advantage of these paradigms is their ability to capture a wide range of threat responses simultaneously. For example, by analyzing in-game decision-making, researchers can observe both internalized responses (such as increased caution or avoidance) and externalized responses (such as heightened aggression or risk-taking) within the same task. While these digital environments would introduce their own forms of noise including varying levels of gaming experience, they offer a more naturalistic setting for observing identity-relevant behavior than word-based tasks. 

Beyond the task design itself, this format may help address the widespread reliance on "WEIRD" (Western, Educated, Industrialized, Rich, and Democratic) samples in psychological research. Game-based measures likely appeal to a broader and more diverse societal demographic than traditional academic surveys. This shift is of particular interest as these populations may exhibit different motivational profiles, including both autonomous and pressured motivations for masculine behavior. Such an approach could provide a more representative view of masculinity threat responses than the predominantly academic samples that are currently overrepresented in the literature. Finally, because the moderation effects proposed by the EDT model are presumably small, moving toward these scalable behavioral formats would allow researchers to achieve the larger sample sizes necessary to reach adequate statistical power for complex interaction effects.

=== Recommendations for Future Research

To improve the detection of masculinity threat effects, future research should prioritize validated instruments with established psychometric properties. While developing new tasks is often necessary, these must undergo rigorous validation to ensure they capture the intended constructs rather than external noise. A successful design must also include clear manipulation checks to confirm the threat was perceived.

In practice, explicit measures often provide higher state-sensitivity than implicit tasks and should be prioritized, provided they are refined to account for social desirability. When the goal is to distinguish between the internalized and externalized pathways proposed by the EDT model, the chosen measures must be capable of clearly separating these distinct responses. Finally, the methodology must match the scale of the research. Because the expected moderation effects are presumably small, researchers should utilize scalable online formats to achieve the large sample sizes necessary for adequate statistical power.

== Validation of the German Motivation for Masculine Behavior Scale 

While the study did not observe the hypothesized moderation effects, it successfully established a psychometrically sound German translation of the MMB scale. Unlike the Word Fragment Completion Task, the MMB scale demonstrated adequate variability even within a highly educated sample. This suggests that the participants' academic background did not lead to a conscious rejection of traditional masculinity norms, which would have otherwise resulted in "floor effects." However, the validation process revealed three specific challenges that required careful refinement of the scale’s factorial and linguistic structure.

The first challenge concerned the relationship between the two latent factors. While the original model by #cite(<stanaland2023masculinity>, form: "prose") suggested they might be orthogonal, the German data required allowing Pressured and Autonomous Motivation to correlate to achieve an acceptable fit. This shift from an orthogonal to a correlated model provides a theoretical solution that aligns with the foundational work on motivation for gendered behaviour @good2010doing. A man's personal ideals (autonomous) do not develop in a vacuum but in constant dialogue with societal expectations (pressured). The internalization of these norms implies an inherent overlap rather than a total separation of motivational sources.
The second challenge involved the poor discriminant validity of Item 9 ("It is important to me not to be feminine"). While this item was theoretically designed to load on the Autonomous Motivation factor, it exhibited significant cross-loading onto the Pressured Motivation factor. This pattern mirrors the observations of #cite(<stanaland2021man>, form: "prose") in the original validation and suggests that the "rejection of femininity" may be a more complex construct. Rather than reflecting a purely autonomous preference, anti-femininity attitudes likely represent a conceptual overlap, driven by a combination of internalized values and perceived external pressures.
The final challenge involved the translation of the scale, specifically regarding how to capture the degree to which a person strives for masculinity. In German, a literal translation of "being masculine" ("männlich sein") can be ambiguous. It may be interpreted by participants as a static biological fact rather than a personal value or goal. To address this, the translation employed a strategic mix of trait-based formulations and agentic, behavioral expressions such as "sich männlich verhalten" (behaving masculinely). This balanced approach ensured the items were not seen as mere descriptions of biological status, but rather as reflections of how much an individual values and actively pursues a masculine identity.

These refinements provide a clear roadmap for future research. By employing a correlated two-factor model and a refined item set, researchers can now reliably assess the motivational drivers of masculine behavior in German-speaking populations.

== Theoretical Considerations

While the psychometric limitations of the Word Fragment Completion Task provide a compelling explanation for the null findings, a purely methodological critique may be incomplete. Recent empirical developments in the field offer alternative perspectives on the precarious manhood thesis, suggesting that masculinity threat responses may be more sensitive to specific social and situational contexts than previously assumed. Exploring these broader theoretical directions may provide a more nuanced understanding of why certain threat effects remain elusive and how future research can better capture the conditions under which they emerge.

=== Expanding the Perspective of Motivational Pathways

One consideration is the potential interplay between the proposed pathways. While the EDT model distinguishes between internalized and externalized responses based on motivation, these paths may not always function in parallel. Alternative frameworks suggest a more sequential relationship, where a threat first triggers internal distress—such as shame or anxiety—which then motivates externalized aggression as a compensatory mechanism to restore status @vescio2025masculinity. If aggression acts as a functional relief for an underlying anxious state @jakupcak2005masculinity, the two pathways are fundamentally linked. This dynamic process would make it difficult for a single measurement point to isolate them as independent outcomes of different motivations.

Beyond the relationship between these pathways, recent evidence suggests that the initial affective experience of gender identity threat may be more symmetric across genders than originally theorized. #cite(<wittlin2024us>, form: "prose") demonstrated that femininity threats regarding physical appearance evoke significant anxiety and self-esteem deficits in women, mirroring the responses previously observed in men. The fact that earlier studies, such as #cite(<bosson2009precarious>, form: "prose"), failed to find this effect might be due to several factors. One possibility is that being told one is "similar to men" may not have been appraised as a significant status loss by all female participants. In certain contemporary social or professional contexts, masculine-coded traits like assertiveness are increasingly viewed as desirable, potentially buffering the intended threat of the feedback.
However, even when a valid threat is administered and triggers distress, a conceptual tension remains for the EDT model when applied to women. If women primarily respond with internalized anxiety, the model would imply a relative lack of the pressured motivation that typically drives externalized aggression. This appears to stand in contrast to research by #cite(<stanaland2021man>, form: "prose") and #cite(<good2010doing>, form: "prose"), who have reliably identified pressured motivation for gendered behavior in women.

This discrepancy suggests that the transition from a perceived "threat" to a specific behavioral response may be influenced by individual control beliefs. According to general stress theory, the quality of a response depends on a person’s sense of agency @lazarus1984stress. Regardless of the underlying motivation, a person’s reaction likely depends on their perceived ability to restore their gender status. When an individual possesses high control beliefs, they may favor engaging in dominant or assertive behaviors designed to re-establish a position of social hierarchy. In this context, the emergence of aggression appears to be contingent upon this perceived agency, serving as a functional, albeit reactive, attempt to alter the social environment and restore standing.
Conversely, when control beliefs are absent, leaving the individual feeling fundamentally powerless to change the situation, the response is likely to shift toward helplessness. In this state of perceived incapacity, the motivation to engage in externalized defense diminishes, leading instead to behavioral withdrawal and internalized distress. Incorporating these perceptions of agency may provide a valuable lens for future research to explain why the same motivational pressure leads to active dominance in some social contexts and psychological retreat in others.

=== Expanding the Perspective of Precarious Manhood

The current results contribute to a growing theoretical body investigating the nature of gender identity and its perceived vulnerability. Traditionally, the precarious manhood thesis has posited a fundamental asymmetry: while womanhood is framed as a biological "given," manhood is viewed as a tenuous social status that must be constantly earned and validated @vandello2013hard. However, the assumption that this vulnerability is unique to men is increasingly being re-evaluated.

As previously discussed, the perceived asymmetry in gender-identity threat responses may stem, in part, from a methodological misalignment in how "threat" is operationalized. In foundational studies, such as those by #cite(<bosson2009precarious>, form: "prose"), women were often "threatened" by being told they were similar to men. Such a stimulus may not be appraised as a significant status loss by many participants, particularly because masculinity is frequently associated with high social status and institutional power. This highlights a fundamental challenge to the precarious manhood thesis itself: it is possible that the tenuous and elusive nature of masculinity is not bound to the gender identity per se, but rather to the maintenance of high social status. If masculinity is synonymous with a dominant position in the social hierarchy, the "precariousness" observed may simply be the psychological anxiety inherent in maintaining any privileged status that is socially conferred rather than biologically inherent. From this perspective, any identity linked to power would be inherently precarious, as it requires constant outward proof to justify its continued possession.

Parallel to this question of social status is the question of how gender identity itself is constructed and maintained. These insights invite future research to move beyond traditional binary assumptions and examine gender identity as a multi-dimensional construct. By viewing precariousness as a potential experience across the gender spectrum, empirical research can be better aligned with the performative nature of gender @butler2002gender. In this view, gender is not a stable, internal essence but an ongoing "doing"—a repetitive social performance that must be constantly maintained. If gender is understood as a continuous act rather than a static state, the risk of its "failure" becomes a shared feature of the human experience rather than a uniquely masculine vulnerability.
For instance, a non-binary individual may experience significant identity precariousness when faced with persistent misgendering or social pressures to conform to a binary category. In such cases, the threat does not stem from a failure to be "masculine" or "feminine" in the traditional sense, but from the social invalidation of their specific gender performance. This broader perspective allows the precarious manhood thesis to adapt to a contemporary landscape where all gendered identities are, to some extent, socially precarious.

== Conclusion

The present study aimed to replicate masculinity threat effects and test predictions of the EDT model in a German sample. None of the four hypotheses were supported: neither main effects of threat on aggressive or anxious cognition nor moderation by pressured or autonomous motivation reached statistical significance. These null findings are attributed to inadequate measurement rather than absence of the underlying phenomena, given the poor psychometric properties of the German Word Fragment Completion Task.
Despite these limitations, the study makes two positive contributions. First, the manipulation checks demonstrate that the masculinity threat paradigm can successfully induce perceived threats in German samples, providing a foundation for future studies with better outcome measures. Second, the validated German translation of the MMB scale enables future research on masculine motivation in German-speaking populations.
Future research on masculinity threat effects should prioritize validated dependent measures with established psychometric properties. Word Fragment Completion Task, while theoretically attractive for their implicit nature, may not transfer reliably across languages and should be thoroughly validated before use in substantive hypothesis testing. Alternative approaches, including self-report measures, behavioral paradigms, and physiological indicators, each carry their own limitations but may provide more reliable assessments of threat-induced cognition and affect. The continued development and validation of masculinity threat paradigms remains an important goal for understanding how gender identity shapes psychological responses to social evaluation.