#import "../utils.typ": *

// Implicit introduction heading level 1
At the core of our being lies our identity: a dynamic, multifaceted self-concept shaped by our personal journeys and the social groups we inhabit. Whether grounded in gender, class, or shared passions, these affiliations influence how we see ourselves, how others perceive us, and the expectations placed upon us. They provide a sense of belonging and purpose, and their norms often serve as guardrails that offer stability among life's unpredictability.
Yet, when these guardrails become too narrow, they risk becoming barriers. Meant to protect, they can instead constrain and limit ourselves.
Few sets of social norms illustrate this tension as vividly as those surrounding masculinity.

== Masculinity Norms and Their Psychological Cost

Masculinity norms influence the lives of men across their entire lifespan, significantly shaping their behavior and experience.
From an early age, boys internalize anti-femininity norms, such as the belief that #quote(attribution: [@blakemore2003children])[boys shouldn't look like girls] This early form of gender policing continues into adolescence, where young men report feeling pressured to engage in heterosexual activity @duckworth2019gender. Additional masculinity norms include emotional restriction, self-reliance, the pursuit of achievement and status, aggression, and rejection of homosexuality @levant1992male. While the content of masculinity norms varies with their cultural background @lease2013cross, these norms consistently shape male behavior and carry significant
psychological and social costs.
This is illustrated when the narrow range of behaviors that is deemed socially acceptable for men conflicts with a man's personal needs, values, or emotions @o1986gender. For example, attempting to meet masculinity expectations, and potentially failing to do so, is associated with elevated stress @pleck1995gender and linked to a range of negative mental health outcomes such as depression and anxiety @blazina1996masculine. Moreover, masculinity norms that enforce status-seeking and dominance-related pressures contribute to aggressive behaviors like sexual violence @rando1998gender.

Although the negative consequences of men's gender role conflict are well-documented @o2008summarizing, the underlying processes through which this strain develops remain poorly understood. To explain why these costs are so persistent, it is crucial to consider how masculinity functions not just as a set of traits, but as a social status that must be continuously earned and maintained.

== Masculinity as a Precarious Social Status

"Men are made, not born": the idea that masculinity functions as a socially granted status rather than a fixed set of traits has been documented across diverse cultures @gilmore1990manhood.
In contrast to womanhood, which is often perceived as a natural, biological outcome, manhood is viewed as a status that must be earned, actively maintained, and socially validated @vandello2013hard.
This notion, coined the _precarious manhood thesis_, has been supported by experimental research using gender-identity threats. In these studies, men and women are typically provided with feedback challenging their respective masculinity or femininity. While both groups are subjected to these threats, only men respond with significant psychological and behavioral shifts, such as shame and anxiety @vandello2008precarious or compensatory aggression and dominance @bosson2009precarious.
These defensive reactions to masculine identity threats have led to the popular characterization of masculinity as _fragile_: the notion that a man's social status as a "real man" is so tenuous that it must be constantly defended and protected @stanaland2023masculinity.
This identity fragility serves as an important link between the psychological strain experienced by the individual and the negative consequences of masculinity norms for broader society.
In a series of studies, researchers have found that masculinity threats provoke physical aggression @bosson2009precarious, ideological dominance and prejudice toward women @dahl2015threats, denial of social inequities @weaver2015justification, anti-gay prejudice @brown2023experimentally, violence toward gay men @parrott2008determinants, and the tolerance of such violence through inaction @schermerhorn2022perceptions. These studies highlight the negative consequences of masculinity norms and emphasize the need for a better understanding of the psychological mechanisms behind this behavior.

A crucial observation in this literature has been the diversity of reactions triggered by masculinity threats. 
Empirical studies have revealed that both anxiety @vandello2008precarious and aggression @bosson2009precarious are typical responses. These responses are mirrored by the psychological strain experienced in men's gender role conflict, which includes depression and anxiety @blazina1996masculine, as well as aggressive behavior @rando1998gender. 
To address why men respond to threats in such divergent ways, recent research has suggested investigating the underlying motivations for conforming to masculine norms as a potential moderator of these responses.

== A Motivational Framework for Masculinity Threat Effects

Although stereotypically masculine behaviors may appear uniform on the surface, the motivations behind them can differ significantly. Men may engage in gender-conforming behavior for autonomous reasons, such as when they freely choose and genuinely value such behavior, or for pressured reasons, because they feel compelled by external expectations or fear of rejection @good2010doing. This distinction between _autonomous_ and _pressured_ _motivation_ for gender-conforming behavior has recently been applied to research on masculinity threats.
In a pioneering study, #cite(<stanaland2021man>, form: "prose") developed the Motivation for Masculine Behavior (MMB) scale to distinguish between these two motivational profiles. Their results demonstrated that men with higher pressured motivation showed significantly more aggressive cognition following a masculinity threat. Crucially, this connection was not explained by men's autonomous motivation, nor by their private regard (i.e., the personal importance they place on being a man). This suggests that the aggressive response is specifically driven by external forces, such as the perceived need to meet social expectations, rather than by intrinsic factors like a personal commitment to masculine values.
While #cite(<stanaland2021man>, form: "prose") tested these motivational predictors for both men and women and induced both masculinity and femininity threats, the aggressive response was only observed and moderated for male participants. This lack of a similar reaction in women further confirms the findings of the precarious manhood thesis, suggesting that the pressure to maintain gender status through compensatory behavior is a uniquely masculine phenomenon.

Building on this evidence, #cite(<stanaland2023masculinity>, form: "prose") introduced the expectancy-discrepancy-threat (EDT) model of masculine identity (@fig:EDT-Model) to explain the differences in masculinity threat responses.

#apa-figure(
  caption: [The Expectancy-Discrepancy-Threat Model of Masculine Identity],
  image("../images/EDTModel.png"),
  label: "fig:EDT-Model",
  note:[Adapted from #cite(<stanaland2023masculinity>, form: "prose"). Men are socialized to conform to norms of masculinity. When experiencing a masculinity threat, different types of self-discrepancies give rise to distinct motivational processes. An actual-ought discrepancy is thought to trigger extrinsic motivation, often resulting in externalized compensatory behaviors (e.g., aggression). In contrast, an actual-ideal discrepancy is believed to foster intrinsic motivation, leading to an internalized compensatory response (e.g., anxiety).]
)

According to this model, boys and men are socialized into rigid masculinity norms and expectations.
Drawing from self-discrepancy theory @higgins1987self, the EDT model proposes that men develop three domains of the self: the actual self (who they believe they are), the ideal self (who they aspire to be), and the ought self (who they feel they should be, based on societal expectations).
When men’s actual selves do not align with these standards during a masculinity threat, they experience identity discrepancies.
Drawing from self-determination theory @deci1987support, the EDT model suggests that these discrepancies produce distinct motivational responses. An actual-ought discrepancy generates a state of extrinsic motivation to reduce tension, which is associated with externalized responses such as aggression. Conversely, an actual-ideal discrepancy produces a state of intrinsic motivation, which tends to result in internalized reactions such as shame or anxiety.
A crucial bridge exists between these situational states and the motivational traits measured by #cite(<stanaland2021man>, form: "prose"). While the MMB scale assesses a man’s general trait-like tendency to feel pressured or autonomous in his masculinity, the EDT model describes the concrete, state-based motivations that arise in response to a specific discrepancy. The increased aggressive threat response observed by #cite(<stanaland2021man>, form: "prose") can thus be understood through this lens: men with higher pressured motivation as a trait likely experience a greater actual-ought discrepancy when threatened, leading to an externalized, aggressive state. Importantly, men are unlikely to experience only one type of discrepancy; rather, they often experience both forms to different extents, depending on how their underlying motivations interact with a given threat.

== The Present Research

While the EDT model provides a compelling theoretical framework for understanding divergent threat responses, empirical testing of these specific pathways remains in its early stages. The present research addresses this gap by investigating the relationship between men's trait motivations for masculine behavior and their situational responses to masculinity threats. In doing so, this study makes several key contributions to the field.

First, it extends existing research on masculinity threat effects by assessing its cross-cultural generalizability within a German sample, determining if the precarious nature of manhood observed in U.S. contexts holds true in a different cultural landscape. 
Second, it provides a direct empirical test of the pathways proposed by the EDT model, specifically examining how underlying motivations for conformity shape the psychological and behavioral outcomes of gender-role strain.
Third, the present research addresses methodological challenges in the field by exploring implicit measures for assessing masculinity threat responses, which may provide a more nuanced understanding of reactions that are often masked in self-report data.

=== Cross-Cultural Generalizability of Masculinity Threat Effects

Much of the foundational research on masculinity threat effects and the precariousness of manhood has been conducted in the United States @stanaland2021man@bosson2009precarious@vandello2008precarious. This raises concerns about the generalizability of these findings, as the United States—particularly the rural South—is often characterized by an "honor"-based culture that emphasizes the aggressive defense of one's reputation @cohen1996insult. In such contexts, aggressive behavior may serve as a norm-consistent response among men whose masculinity is closely tied to external validation @jin2021precarious.

However, the precariousness of manhood appears to be a more universal phenomenon rather than one unique to the United States. This idea was famously proposed by #cite(<gilmore1990manhood>, form: "prose"), who argued that manhood is a "produced" and "contested" status across nearly all cultures. This anthropological observation has been supported by recent large-scale investigations documenting widespread beliefs in the tenuous nature of masculinity across 62 nations @bosson2021psychometric. 
While the intensity of threat responses may scale with broader societal patterns, like gender equality, the underlying precariousness of manhood persists even in egalitarian societies. For instance, men in both Poland and Norway have been found to respond to masculinity threats with increased aggressive cognition @valved2021gender and reduced support for gender equality @kosakowska2016if.
This suggests that Germany provides a relevant context for testing these theories, despite its high ranking in gender equality #citeWithPrefix(prefix: "Rank 7/146;", keys: <wef2024gendergap>). The Norwegian case is particularly instructive: even in a society with a higher equality ranking than Germany #citeWithPrefix(prefix: "Rank 3/146;", keys: <wef2024gendergap>), masculinity threats still successfully triggered compensatory aggressive cognition @valved2021gender. These findings indicate that structural progress toward gender equality does not necessarily dissolve the psychological association between manhood and social status. Consequently, if manhood remains a precarious status in Germany, a situational threat should activate a masculinity threat effect, characterized by the psychological strain and compensatory pathways described by the EDT model. Accordingly, the following hypotheses are proposed:

- *Hypothesis 1a*: Men exposed to a masculinity threat will exhibit higher levels of aggressive cognition than men who do not receive a masculinity threat.
- *Hypothesis 1b*: Men exposed to a masculinity threat will exhibit higher levels of anxious cognition than men who do not receive a masculinity threat.

=== Testing Motivational Predictors of Masculinity Threat Effects

Although the EDT model is theoretically compelling, empirical support for its proposed pathways remains limited. Two studies have found that pressured motivation to be masculine moderates aggressive threat responses, with men higher in pressured motivation showing increased aggressive cognition following a masculinity threat @stanaland2021man @stanaland2024adolescent. However, the second pathway proposing that autonomous motivation moderates internalized threat responses such as anxiety remains untested.

Moreover, the model faces conceptual challenges from alternative frameworks that propose a sequential relationship between internalized and externalized threat responses. These frameworks suggest that men may initially experience internal distress (e.g., shame or anxiety), which then escalates into outward aggression @vescio2025masculinity. In this view, externalized responses serve as compensation for internal distress. This pattern is rooted in research showing that the expression of anger relieves feelings of discomfort @jakupcak2005masculinity. These competing perspectives highlight the need for careful empirical testing of the EDT model's predictions.

To explain inter-individual differences in men's responses to masculinity threats, the present research tests the EDT model's predictions. According to the model, pressured motivation is associated with externalized responses: men primarily motivated by external expectations are more likely to experience an actual-ought discrepancy when threatened, which activates extrinsic motivation and manifests as aggression. Conversely, autonomous motivation is linked to internalized responses: men who genuinely value masculine ideals may experience an actual-ideal discrepancy when threatened, resulting in anxiety or shame. Accordingly, the following hypotheses are proposed:

- *Hypothesis 2a*: Pressured motivation to conform to masculinity norms increases the positive effect of a masculinity threat (compared to the control condition) on aggressive cognition.
- *Hypothesis 2b*: Autonomous motivation to conform to masculinity norms increases the positive effect of a masculinity threat (compared to the control condition) on anxious cognition.

=== Addressing Methodological Limitations

Investigating masculinity threat responses presents a significant methodological challenge: the tendency for men to monitor and regulate their outward behavior to align with gender norms. While prior research has frequently relied on self-report or overt behavioral measures, these can be problematic when studying gender-role strain. Internalized emotional responses, such as shame or anxiety, are often incongruent with dominant masculinity standards and may be consciously downplayed or suppressed in explicit reports. Furthermore, aggressive behavioral responses may sometimes reflect the enactment of socially learned scripts rather than genuine psychological reactivity.

To address these limitations, the present study focuses on cognitive activation, specifically the implicit accessibility of aggressive and anxious concepts, rather than self-reported states. We employ the Word Fragment Completion Task, an implicit measure in which participants complete word fragments that can be resolved as either target words (e.g., related to aggression or anxiety) or neutral alternatives. This task has been successfully utilized to assess aggressive cognition @stanaland2021man @stanaland2024adolescent and anxious cognition @vandello2008precarious following masculinity threats.
By measuring the ease with which these concepts come to mind, the Word Fragment Completion Task provides a window into underlying mental processes that are less susceptible to social desirability bias. This approach allows for a more sensitive and direct examination of how masculinity threats are internally processed, capturing reactions that might otherwise be masked by the pressure to adhere to traditional masculine self-presentation.