#import "@preview/versatile-apa:7.1.2": apa-figure

// Implicit introduction heading level 1
At the core of our being lies our identity — a dynamic, multifaceted self-concept shaped by our personal journeys and the social groups we inhabit. Whether grounded in gender, ethnicity, class, or shared passions, these affiliations influence how we see ourselves, how others perceive us, and the expectations placed upon us. They provide a sense of belonging and purpose, and their norms often serve as guardrails — offering stability amid the chaos and unpredictability of life. Yet, when these guardrails become too narrow, too rigid, they risk becoming barriers. Meant to keep us safe, they can instead steer us toward collision, limiting growth and distorting our path.
== Masculinity Norms and Their Psychological Cost
One particularly rigid and influential set of social norms are those associated with masculinity. From an early age, boys internalize anti-femininity norms, such as the belief that #quote(attribution: [@blakemore2003children])[boys shouldn’t look like girls] This early form of gender policing continues into adolescence, where young men report feeling pressured to engage in heterosexual activity @duckworth2019gender. Further masculinity norms include emotional restriction, self-reliance, the pursuit of achievement and status, aggression, and rejection of homosexuality @levant1992male. While the content of masculinity norms varies with its cultural background, they all shape male behavior and experience @lease2013cross.

Conforming to rigid masculinity norms carries significant psychological and social costs. Attempting — and potentially failing — to meet these expectations is associated with elevated stress @pleck1995gender and linked to a range of negative mental health outcomes such as depression and anxiety @blazina1996masculine. Moreover, status-seeking and dominance-related pressures contribute to aggressive behaviors like sexual violence @rando1998gender.

The psychological strain that occurs when a man's personal needs, values, or emotions conflict with the narrow range of behaviors deemed socially acceptable for men is referred to as men’s gender role conflict @o1986gender. Although the negative consequences of this conflict are well documented @o2008summarizing, the processes through which this strain develops remain poorly understood. To understand why the costs of masculinity norms are so persistent, it is crucial to consider how masculinity is not just a set of traits, but a social status that must be earned and maintained.


== Masculinity as a Precarious Social Status
“Men are made, not born”: the idea that masculinity functions as a socially conferred status rather than a fixed set of traits has been documented across diverse cultures @gilmore1990manhood. In contrast to womanhood — which is often perceived as a natural and biological outcome — manhood is viewed as a status that must be earned, actively maintained, and socially validated (precarious manhood thesis; Vandello & Bosson, 2013). This structural fragility becomes especially apparent when men face threats to their masculinity, often eliciting _internalized_ responses such as shame and anxiety @vandello2008precarious, or _externalized_ responses such as aggression and dominance @bosson2009precarious. Men’s aggressive threat response has led to the characterization of masculinity as _fragile_ - the notion that a man’s social status as a “real man” is so tenuous that it must be constantly defended.

The precarious nature of masculinity bears significant implications not only for individuals but also for broader society. Masculinity threats provoke physical aggression @bosson2009precarious, ideological dominance and prejudice toward women @dahl2015threats, denial of social inequities @weaver2015justification, anti-gay prejudice @brown2023experimentally, violence toward gay men @parrott2008determinants, and the tolerance of such violence through inaction @schermerhorn2022perceptions.

While the precarious manhood thesis offers a compelling account of why masculinity threats provoke defensive behaviors, it also reveals a divergence in the nature of these responses. Both anxious withdrawal and aggressive assertion appear to be plausible outcomes - consistent with the psychological strain men experience in trying to meet rigid gender expectations and the need to repeatedly prove one’s masculinity through dominant behavior. However, the factors that determine whether a threat leads to internalized or externalized reactions remain unclear. To address this gap, it is critical to examine the underlying motivations for conforming to masculine norms, which may help explain why men respond to threats in different ways.

== A Motivational Framework for Masculinity Threats

Although stereotypically masculine behaviors may appear uniform on the surface, the motivations behind them can differ significantly. For instance, one man might work out because he genuinely enjoys the activity and finds it personally meaningful, reflecting _autonomous motivation_. Another might exercise primarily because he feels it is expected of him and fears rejection, demonstrating _pressured motivation_.
This distinction in motivations for masculine behavior has important implications for how men respond to threats to their masculine identity. Men with higher pressured motivation to conform to masculinity norms respond to such threats with increased aggression @stanaland2021man. This interaction could not be explained via men’s autonomous motivation or their collective self-esteem — that is, the degree to which they derive pride and self-worth from identifying as a man.

Building on this evidence, #cite(<stanaland2023masculinity>, form: "prose") introduced the expectancy-discrepancy-threat (EDT) model of masculine identity (@fig:EDT-Model). According to this model, boys and men are socialized into rigid masculinity norms and expectations. Drawing from self-discrepancy theory @higgins1987self the EDT model posits that in response to this socialization process men develop three domains of the self: The actual self (who they believe they are), the ideal self (who they aspire to be), and the ought self (who they feel they should be, based on societal expectations). In the case that men's actual-selves do not align with their ideal or ought selves — as in the context of a masculinity threat — they may experience two types of identity discrepancies: one between who they are and who they believe they should be (actual-ought), and another between who they are and who they aspire to be (actual-ideal). Drawing from self-determination theory @deci1987support the EDT model suggests that an actual-ought discrepancy generates extrinsic motivation to reduce the tension which is associated with externalized responses to threat, such as aggression. On the other hand, an actual-ideal discrepancy produces intrinsic motivation that tends to result in internalized reactions, such as shame or anxiety. Importantly, men are unlikely to experience only one type of discrepancy; rather, they often experience both forms to different extents, depending on their underlying motivations to conform to masculinity norms.

#apa-figure(
  caption: [The Expectancy-Discrepancy-Threat Model of Masculine Identity],
  image("../images/EDTModel.png"),
  label: "fig:EDT-Model",
  note:[Men are socialized to conform to societal norms of masculinity. Different types of self-discrepancies—between the actual self (how one perceives oneself), the ideal self (who one wishes to be), and the ought self (who one believes they should be)—can give rise to distinct motivational processes. When masculinity is threatened, an actual-ought discrepancy is thought to elicit extrinsic motivation, often resulting in externalized compensatory behaviors (e.g. aggression). In contrast, an actual-ideal discrepancy  is believed to foster intrinsic motivation, leading to an internalized compensatory response (e.g. anxiousness).]
)
#linebreak()

The EDT model of masculine identity offers a compelling framework for understanding the diverse emotional and behavioral responses men exhibit when their masculinity is challenged. However, despite its theoretical richness, empirical research testing the model remains limited, particularly in diverse cultural contexts. To address these gaps, the present study seeks to provide further empirical support for the EDT model by examining how men respond to masculinity threats and how these responses are shaped by underlying motivational factors.

== The Present Research
By investigating masculinity threat responses in a novel cultural context using a theoretically grounded motivational framework, the present research makes several key contributions. First, it extends the EDT model by assessing its cross-cultural generalizability. Second, it addresses limited empirical evidence for the pathways proposed by the EDT model. Third, it directly tests the model’s core predictions using implicit cognitive measures that capture both internalized and externalized threat responses. Through this multifaceted approach, the study aims to clarify the psychological processes that underlie fragile masculinity and deepen our understanding of how and why men respond differently when their gender identity is challenged.

=== Cross-Cultural Generalizability of Masculinity Threat Effects

Most research on fragile masculinity and the precariousness of manhood has been conducted in the United States. This raises concerns about the generalizability of these findings to other cultural contexts with differing gender norms and expectations. For example, the United States — particularly rural, Southern regions — is often described as an individualistic and “honor”-based culture that simultaneously emphasizes and challenges men’s masculinity @cohen1996insult. In such contexts, aggressive behavior may serve as a norm-consistent response among men whose masculinity is closely tied to external validation @stanaland2022fragile.

In support of the idea that masculine identity fragility also manifests outside the United States are widespread beliefs about the precariousness of manhood (i.e. the belief that manhood has to be earned and publicly demonstrated) including Germany and other European nations @bosson2021psychometric. This is further supported by Polish and Norwegian men, who responded to masculinity threats with increased aggressive cognition @valved2021gender and reduced support for gender equality @kosakowska2016if. Notably, cross-cultural differences in threat responses appear to correspond with broader societal patterns: countries with higher gender inequality and lower human development scores tend to show stronger beliefs in the precariousness of manhood @bosson2021psychometric. This is consistent with the stronger threat response observed in Polish men compared to Norwegian men @valved2021gender.

Taken together, the prevalence of precarious manhood beliefs and empirical support from European populations make it plausible to expect compensatory responses to a masculinity threat in the present study. Although the present research is conducted in Germany — a country with relatively high gender equality (Rank 7/146; World Economic Forum, 2024) - it is expected that threat effects still emerge, albeit potentially with smaller effect sizes. This expectation is supported by prior findings showing that in Norway, a country with even higher levels of gender equality (Rank 3/146; World Economic Forum, 2024), men still exhibited increased aggressive cognition following a masculinity threat @valved2021gender. Accordingly, it is hypothesized: 

==== Hypothesis 1a
Men exposed to a masculinity threat will exhibit higher levels of aggressive cognition than men receiving neutral feedback.

==== Hypothesis 1b
Men exposed to a masculinity threat will exhibit higher levels of anxious cognition than men receiving neutral feedback

=== Testing Motivational Predictors of Threat Response

To explain inter-individual differences in men’s responses to masculinity threats, the present research aims to test the EDT model of masculine identity by applying its predictions in a novel cultural context. Although theoretically compelling, empirical support for the EDT model remains limited. Moreover, the model faces conceptual challenges from alternative frameworks that propose a sequential relationship between internalized and externalized threat responses - suggesting, that men may initially experience internal distress (e.g., shame or anxiety), which then escalates into outward aggression @vescio2025masculinity. Here, externalized responses serve as a compensation to internal distress and is rooted in research that the expression of anger relieves feelings of discomfort @jakupcak2005masculinity. These competing perspectives highlight the need for rigorous empirical testing of the EDT model’s predictions. 

According to the EDT model, pressured motivation - the external pressure to conform to masculine norms - is associated with externalized responses to masculinity threats, such as increased aggressive cognition. This pattern has been observed in both adult @stanaland2021man and adolescent @stanaland2024adolescent samples. Thus it is hypothesized

==== Hypothesis 2a
External pressure to conform to masculinity norms increases the positive effect of a masculinity threat (compared to a neutral feedback) on aggressive cognition.

Conversely, the EDT model posits that autonomous motivation is linked to internalized responses to masculinity threats, such as anxiety or shame. However, this prediction has not yet been empirically tested. Prior research has focused mainly on externalized responses, particularly aggression, leaving a gap in our understanding of how masculinity threats may also elicit internal distress. The present study addresses this gap by examining whether autonomous motivation predicts anxious cognition in response to a masculinity threat. Specifically it is hypothesized:

==== Hypothesis 2b
Internal pressure to conform to masculinity norms increases the positive effect of a masculinity threat (compared to a neutral feedback) on anxious cognition.

=== Addressing Methodological Limitations
Finally, methodological challenges persist in studying masculinity threat and the EDT model. While prior research has often operationalized masculinity threat responses through observable behaviors (e.g., aggression, dominance, social withdrawal), this study focuses on cognitive activation-specifically, aggressive and anxious cognition. This approach offers two key advantages. First, internalized emotional responses such as shame or anxiety are often incongruent with dominant masculinity norms and may be consciously downplayed or denied in self-report or behavioral tasks. Second, aggressive actions may sometimes reflect socially learned scripts rather than genuine emotional reactivity. Implicit cognitive tasks, such as the Word Fragment Completion Task (WFCT), are less susceptible to social desirability bias and provide a more direct measure of underlying threat-relevant mental processes. Thus, assessing cognitive activation allows for a more sensitive and nuanced examination of how masculinity threats are internally processed.